parameters:
    # Adds a fallback DATABASE_URL if the env var is not set. This allows you
    # to run cache:warmup even if your environment variables are not available
    # yet. You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                url: '%env(DATABASE_URL)%'
                <<: &connection_configuration
                    # Remove from doctrine refresh_token (Refresh JWT token table)
                    # Remove from doctrine messenger_messages (Symfony messenger queue table)
                    # Remove from doctrine core_staff_log (Old table kept for reference)
                    schema_filter: '/^(?!refresh_token|messenger_messages|core_staff_log).*$/'
                    driver_class: 'Facile\DoctrineMySQLComeBack\Doctrine\DBAL\Driver\PDOMySql\Driver'
                    default_table_options:
                        charset: utf8mb4
                        collate: utf8mb4_unicode_ci
                    mapping_types:
                        enum: string
                    options:
                        x_reconnect_attempts: 3
            # connection dedicated to Doctrine Migration bundle
            migration:
                url: '%env(DATABASE_URL_MIGRATION)%'
                <<: *connection_configuration
        types:
            bitmask: Unilend\Core\Doctrine\Types\BitmaskType
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        default_entity_manager: default
        entity_managers:
            default:
                connection: default
                auto_mapping: true
                <<: &entity_manager_configuration
                    naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                    mappings:
                        Unilend\Syndication:
                            is_bundle: false
                            type: annotation
                            dir: '%kernel.project_dir%/src/Syndication/Entity'
                            prefix: 'Unilend\Syndication\Entity'
                            alias: Unilend
                        Unilend\Core:
                            is_bundle: false
                            type: annotation
                            dir: '%kernel.project_dir%/src/Core/Entity'
                            prefix: 'Unilend\Core\Entity'
                            alias: Unilend\Core
                        Unilend\Agency:
                            is_bundle: false
                            type: annotation
                            dir: '%kernel.project_dir%/src/Agency/Entity'
                            prefix: 'Unilend\Agency\Entity'
                            alias: Unilend\Agency
                    hydrators:
                        HYDRATE_COLUMN: Unilend\Core\Doctrine\ORM\ColumnHydrator
                    filters:
                        softdeletable:
                            class: 'Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter'
                            enabled: true
                        term:
                            class: Unilend\Agency\Doctrine\Filter\TermFilter
                            enabled: true
            # entity manager dedicated to Doctrine Migration bundle (Doctrine Migration bundle ignores the option --conn, if it finds some entity manager)
            migration:
                connection: migration
                auto_mapping: false
                <<: *entity_manager_configuration
services:
    doctrine.result_cache_provider:
        class: Symfony\Component\Cache\DoctrineProvider
        public: false
        arguments:
            - '@doctrine.result_cache_pool'
    doctrine.system_cache_provider:
        class: Symfony\Component\Cache\DoctrineProvider
        public: false
        arguments:
            - '@doctrine.system_cache_pool'

framework:
    cache:
        pools:
            doctrine.result_cache_pool:
                adapter: cache.app
            doctrine.system_cache_pool:
                adapter: cache.system
