doctrine_migrations:
    migrations_paths:
        'DoctrineMigrations': '%kernel.project_dir%/src/Core/Migrations'
    em: migration
    organize_migrations: false
    all_or_nothing: true
    storage:
        table_storage:
            table_name: 'core_migration_versions'