framework:
    secret: '%env(APP_SECRET)%'
    csrf_protection: true
    http_method_override: true
    trusted_hosts: ~
    session:
        handler_id: ~
        cookie_samesite: lax
        cookie_domain: .kls-platform.com
    php_errors:
        log: true
    form:
        csrf_protection:
            field_name: _csrf
    secrets:
        # This is a default value, but I still put it here to remain the usage of SYMFONY_DECRYPTION_SECRET as an Environment Variable
        decryption_env_var: 'base64:default::SYMFONY_DECRYPTION_SECRET'
