Unilend\Bundle\CoreBusinessBundle\Entity\Clients:
    properties:
        nom:
            - NotBlank: ~
            - Length:
                min: 2
            - Regex:
                pattern: '/[^A-zÀ-ÿ\s\-]+/i'
                match: false
        nomUsage:
            - Regex:
                pattern: '/[^A-zÀ-ÿ\s\-]+/i'
                match: false
                groups: [lender_person]
        prenom:
            - NotBlank: ~
            - Regex:
                pattern: '/[^A-zÀ-ÿ\s\-]+/i'
                match: false
            - Length:
                min: 2
        naissance:
            - Date: {groups: [lender_person]}
        idPaysNaissance:
            - NotNull: {groups: [lender_person]}
            - Length:
                min: 1
                max: 3
                groups: [lender_person]
            - Type:
                type: integer
                groups: [lender_person]
        inseeBirth:
            - Length:
                min: 5
                groups: [lender_person]
        idNationalite:
            - NotNull: {groups: [lender_person]}
            - Length:
                min: 1
                max: 3
                groups: [lender_person]
            - Type:
                type: integer
                groups: [lender_person]
        telephone:
            - Regex:
                pattern: '/[^0-9\s\-\+]/'
                match: false
            - Length:
                min: 10
        mobile:
            - Regex:
                pattern: '/[^0-9\s\-\+]/'
                match: false
            - Length:
                min: 10
        email:
            - NotBlank: ~
            - Email:
        secreteQuestion:
            - NotBlank: ~
        secreteReponse:
            - NotBlank: ~
        fundsOrigin:
            - NotNull: ~
            - Length:
                min: 1
                max: 3
            - Type: integer
        fonction:
            - NotBlank: {groups: [lender_legal_entity]}
            - Regex:
                pattern: '/[^A-zÀ-ÿ\s\-]+/i'
                match: false
                groups: [lender_legal_entity]
            - Length:
                min: 2
                groups: [lender_legal_entity]





