Unilend\Bundle\CoreBusinessBundle\Entity\ClientsAdresses:
    properties:
        cp:
            - Type: alnum
        ville:
            - Regex:
                pattern: '/[^A-zÀ-ÿ0-9\s\-]+/'
                match: false
        idPays:
            - Length:
                min: 1
                max: 3
            - Type: integer
        villeFiscal:
            - Regex:
                pattern: '/[^A-zÀ-ÿ0-9\s\-]+/'
                match: false
        cpFiscal:
            - Type: alnum
        idPaysFiscal:
            - Length:
                min: 1
                max: 3
            - Type: integer
