security:
    encoders:
        Unilend\Bundle\FrontBundle\Security\User\BaseUser:
            id: unilend.frontbundle.security.password_encoder
        md5:
            algorithm: md5
            encode_as_base64: false
            iterations: 0

    providers:
        unilend_front_bundle:
            id: unilend.frontbundle.security.user_provider
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        default:
            pattern: /
            anonymous: ~
            guard:
                authenticators:
                    - unilend.frontbundle.security.login_authenticator
            logout:
                path: logout
                target: /

    access_denied_url: /login

    access_control:
        - { path: ^/espace-emprunteur/securite, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/espace-emprunteur, roles: ROLE_BORROWER }
        - { path: ^/conseil-cip(|/.*)$, roles: ROLE_LENDER }
        - { path: ^/statistiques/, roles: IS_AUTHENTICATED_ANONYMOUSLY, ips: [192.168.110.1, 92.154.10.41, 192.168.1.196] }
        - { path: ^/statistiques/, roles: ROLE_NO_ACCESS }
