parameters:
    # Adds a fallback LOCAL_PROJECT_DIR if the env var is not set.
    # You SHOULD NOT change this value, INSTEAD you should defined it in .env.local
    env(LOCAL_PROJECT_DIR): 'path/to/the/project/in/your/local/host/machine'

framework:
    ide: 'phpstorm://open?file=%%f&line=%%l&/var/www/>%env(LOCAL_PROJECT_DIR)%'
