imports:
  - { resource: services.yaml }

services:
  _defaults:
    autowire: true
    autoconfigure: true

  Unilend\Test\Core\DataFixtures\:
    resource: '%kernel.project_dir%/tests/Core/DataFixtures'

  Unilend\Test\Syndication\DataFixtures\:
    resource: '%kernel.project_dir%/tests/Syndication/DataFixtures'

  Unilend\Test\Agency\DataFixtures\:
    resource: '%kernel.project_dir%/tests/Agency/DataFixtures'